// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlo-pBaIV7gsCU6NbWyEfM_T4dmncHtnc',
    appId: '1:1063670954198:web:649319cf757fd49e507177',
    messagingSenderId: '1063670954198',
    projectId: 'nspo-b03b4',
    authDomain: 'nspo-b03b4.firebaseapp.com',
    storageBucket: 'nspo-b03b4.appspot.com',
    measurementId: 'G-NFBBNFBMXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2SyMlXPYUArpVy-0fVL6NMYlPUGFmeac',
    appId: '1:1063670954198:android:690eaeceafb0d972507177',
    messagingSenderId: '1063670954198',
    projectId: 'nspo-b03b4',
    storageBucket: 'nspo-b03b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaWRJAYFw0Ok9G6GmKrSyApIH3qAOfKc',
    appId: '1:1063670954198:ios:082b9da397b897e9507177',
    messagingSenderId: '1063670954198',
    projectId: 'nspo-b03b4',
    storageBucket: 'nspo-b03b4.appspot.com',
    iosBundleId: 'com.ahmedmorsi.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgaWRJAYFw0Ok9G6GmKrSyApIH3qAOfKc',
    appId: '1:1063670954198:ios:fa6b9e27089ce49c507177',
    messagingSenderId: '1063670954198',
    projectId: 'nspo-b03b4',
    storageBucket: 'nspo-b03b4.appspot.com',
    iosBundleId: 'com.nspo.nspo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlo-pBaIV7gsCU6NbWyEfM_T4dmncHtnc',
    appId: '1:1063670954198:web:c4f9d4b8333bc71a507177',
    messagingSenderId: '1063670954198',
    projectId: 'nspo-b03b4',
    authDomain: 'nspo-b03b4.firebaseapp.com',
    storageBucket: 'nspo-b03b4.appspot.com',
    measurementId: 'G-M7L2XVW67J',
  );

}